### ISSUE TITLE
Use module Forever to run indexing

### ISSUE THREAD

**Issue by eklem** [eklem/life-index#14]
The Forever module is good for two reasons. 
- will keep process alive
- can be stopped from crontab so indexing can be done peacefully

**Comment by mewwts** [comment]
This is kind of cool: https://github.com/substack/psy

**Comment by eklem** [comment]
Thanks @mewwts ! Lesser options are good, I only need start and stop I think". I'll test [psy](https://github.com/substack/psy)

**Comment by eklem** [comment]
And working!

**Comment by mewwts** [comment]
:+1:
